SELECT x.*
, CEIL(cnt_group_org*1000/cnt_ward)/10||'%' stamm_procent_for_all
, ro.name 
, AMB_ND10.okproc_AMB_ND10 AMB_ND10 
, AMC_ND20.okproc_AMC_ND20 AMC_ND20 
, AMK_ND30.okproc_AMK_ND30 AMK_ND30 
, AMP_ND10.okproc_AMP_ND10 AMP_ND10 
, ATM_ND30.okproc_ATM_ND30 ATM_ND30 
, CAZ_ND30.okproc_CAZ_ND30 CAZ_ND30 
, CFP_ND75.okproc_CFP_ND75 CFP_ND75 
, CHL_ND30.okproc_CHL_ND30 CHL_ND30 
, CIP_ND_5.okproc_CIP_ND_5 CIP_ND_5 
, CLI_ND15.okproc_CLI_ND15 CLI_ND15 
, CRO_ND30.okproc_CRO_ND30 CRO_ND30 
, CSL_ND30.okproc_CSL_ND30 CSL_ND30 
, CTR_ND10.okproc_CTR_ND10 CTR_ND10 
, DOR_ND10.okproc_DOR_ND10 DOR_ND10 
, ERY_ND15.okproc_ERY_ND15 ERY_ND15 
, FEP_ND30.okproc_FEP_ND30 FEP_ND30 
, FLU_ND25.okproc_FLU_ND25 FLU_ND25 
, FOS_ND200.okproc_FOS_ND200 FOS_ND200 
, GEN_ND10.okproc_GEN_ND10 GEN_ND10 
, IPM_ND10.okproc_IPM_ND10 IPM_ND10 
, ITR_ND8.okproc_ITR_ND8 ITR_ND8 
, KET_ND15.okproc_KET_ND15 KET_ND15 
, LNZ_ND30.okproc_LNZ_ND30 LNZ_ND30 
, LVX_ND5.okproc_LVX_ND5 LVX_ND5 
, MEM_ND10.okproc_MEM_ND10 MEM_ND10 
, NIT_ND300.okproc_NIT_ND300 NIT_ND300 
, NOR_ND10.okproc_NOR_ND10 NOR_ND10 
, NYS_ND50.okproc_NYS_ND50 NYS_ND50 
, OXA_ND1.okproc_OXA_ND1 OXA_ND1 
, PIP_ND100.okproc_PIP_ND100 PIP_ND100 
, PNV_ND10.okproc_PNV_ND10 PNV_ND10 
, RIF_ND5.okproc_RIF_ND5 RIF_ND5 
, SAM_ND10.okproc_SAM_ND10 SAM_ND10 
, STR_ND10.okproc_STR_ND10 STR_ND10 
, TCY_ND30.okproc_TCY_ND30 TCY_ND30 
, TOB_ND10.okproc_TOB_ND10 TOB_ND10 
, VAN_ND30.okproc_VAN_ND30 VAN_ND30 
, VOR_ND1.okproc_VOR_ND1 VOR_ND1 
FROM (
SELECT x.*, cnt_ward FROM (
SELECT ward, group_org, COUNT(group_org) cnt_group_org FROM (
SELECT x.ward, group_org FROM (
SELECT CASEWHEN(rs_org IS NULL,s.organism,rs_org) group_org, s.organism ogm, s.* FROM surgery17_3 s 
LEFT JOIN (SELECT rs_org, ol.* FROM rs_org_org roo,ORGLIST ol, (SELECT MIN(id) mid FROM ORGLIST ol GROUP BY org) x
WHERE ol.org=roo.org AND x.mid=ol.id) x ON x.org=s.organism 
) x
) GROUP BY ward, group_org
) x, (SELECT WARD, COUNT(WARD) cnt_WARD FROM surgery17_3 GROUP BY WARD) y
WHERE x.ward=y.ward
) x  LEFT JOIN rs_org ro ON rs_org=group_org
 LEFT JOIN (SELECT ward ward_AMB_ND10, group_org group_org_AMB_ND10 , CASEWHEN(all_AMB_ND10>0, CEIL(ok_AMB_ND10*1000/all_AMB_ND10)/10,0) okproc_AMB_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_AMB_ND10) ok_AMB_ND10, SUM(a_AMB_ND10) all_AMB_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(AMB_ND10>s,1,0) s_AMB_ND10, CASEWHEN(s is null,0,1) a_AMB_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE AMB_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='AMB_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) AMB_ND10 on x.ward=AMB_ND10.ward_AMB_ND10 and x.group_org=AMB_ND10.group_org_AMB_ND10 
 LEFT JOIN (SELECT ward ward_AMC_ND20, group_org group_org_AMC_ND20 , CASEWHEN(all_AMC_ND20>0, CEIL(ok_AMC_ND20*1000/all_AMC_ND20)/10,0) okproc_AMC_ND20, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_AMC_ND20) ok_AMC_ND20, SUM(a_AMC_ND20) all_AMC_ND20 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(AMC_ND20>s,1,0) s_AMC_ND20, CASEWHEN(s is null,0,1) a_AMC_ND20, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE AMC_ND20 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='AMC_ND20') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) AMC_ND20 on x.ward=AMC_ND20.ward_AMC_ND20 and x.group_org=AMC_ND20.group_org_AMC_ND20 
 LEFT JOIN (SELECT ward ward_AMK_ND30, group_org group_org_AMK_ND30 , CASEWHEN(all_AMK_ND30>0, CEIL(ok_AMK_ND30*1000/all_AMK_ND30)/10,0) okproc_AMK_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_AMK_ND30) ok_AMK_ND30, SUM(a_AMK_ND30) all_AMK_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(AMK_ND30>s,1,0) s_AMK_ND30, CASEWHEN(s is null,0,1) a_AMK_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE AMK_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='AMK_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) AMK_ND30 on x.ward=AMK_ND30.ward_AMK_ND30 and x.group_org=AMK_ND30.group_org_AMK_ND30 
 LEFT JOIN (SELECT ward ward_AMP_ND10, group_org group_org_AMP_ND10 , CASEWHEN(all_AMP_ND10>0, CEIL(ok_AMP_ND10*1000/all_AMP_ND10)/10,0) okproc_AMP_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_AMP_ND10) ok_AMP_ND10, SUM(a_AMP_ND10) all_AMP_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(AMP_ND10>s,1,0) s_AMP_ND10, CASEWHEN(s is null,0,1) a_AMP_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE AMP_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='AMP_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) AMP_ND10 on x.ward=AMP_ND10.ward_AMP_ND10 and x.group_org=AMP_ND10.group_org_AMP_ND10 
 LEFT JOIN (SELECT ward ward_ATM_ND30, group_org group_org_ATM_ND30 , CASEWHEN(all_ATM_ND30>0, CEIL(ok_ATM_ND30*1000/all_ATM_ND30)/10,0) okproc_ATM_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_ATM_ND30) ok_ATM_ND30, SUM(a_ATM_ND30) all_ATM_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(ATM_ND30>s,1,0) s_ATM_ND30, CASEWHEN(s is null,0,1) a_ATM_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE ATM_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='ATM_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) ATM_ND30 on x.ward=ATM_ND30.ward_ATM_ND30 and x.group_org=ATM_ND30.group_org_ATM_ND30 
 LEFT JOIN (SELECT ward ward_CAZ_ND30, group_org group_org_CAZ_ND30 , CASEWHEN(all_CAZ_ND30>0, CEIL(ok_CAZ_ND30*1000/all_CAZ_ND30)/10,0) okproc_CAZ_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_CAZ_ND30) ok_CAZ_ND30, SUM(a_CAZ_ND30) all_CAZ_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(CAZ_ND30>s,1,0) s_CAZ_ND30, CASEWHEN(s is null,0,1) a_CAZ_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE CAZ_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='CAZ_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) CAZ_ND30 on x.ward=CAZ_ND30.ward_CAZ_ND30 and x.group_org=CAZ_ND30.group_org_CAZ_ND30 
 LEFT JOIN (SELECT ward ward_CFP_ND75, group_org group_org_CFP_ND75 , CASEWHEN(all_CFP_ND75>0, CEIL(ok_CFP_ND75*1000/all_CFP_ND75)/10,0) okproc_CFP_ND75, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_CFP_ND75) ok_CFP_ND75, SUM(a_CFP_ND75) all_CFP_ND75 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(CFP_ND75>s,1,0) s_CFP_ND75, CASEWHEN(s is null,0,1) a_CFP_ND75, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE CFP_ND75 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='CFP_ND75') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) CFP_ND75 on x.ward=CFP_ND75.ward_CFP_ND75 and x.group_org=CFP_ND75.group_org_CFP_ND75 
 LEFT JOIN (SELECT ward ward_CHL_ND30, group_org group_org_CHL_ND30 , CASEWHEN(all_CHL_ND30>0, CEIL(ok_CHL_ND30*1000/all_CHL_ND30)/10,0) okproc_CHL_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_CHL_ND30) ok_CHL_ND30, SUM(a_CHL_ND30) all_CHL_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(CHL_ND30>s,1,0) s_CHL_ND30, CASEWHEN(s is null,0,1) a_CHL_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE CHL_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='CHL_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) CHL_ND30 on x.ward=CHL_ND30.ward_CHL_ND30 and x.group_org=CHL_ND30.group_org_CHL_ND30 
 LEFT JOIN (SELECT ward ward_CIP_ND_5, group_org group_org_CIP_ND_5 , CASEWHEN(all_CIP_ND_5>0, CEIL(ok_CIP_ND_5*1000/all_CIP_ND_5)/10,0) okproc_CIP_ND_5, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_CIP_ND_5) ok_CIP_ND_5, SUM(a_CIP_ND_5) all_CIP_ND_5 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(CIP_ND_5>s,1,0) s_CIP_ND_5, CASEWHEN(s is null,0,1) a_CIP_ND_5, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE CIP_ND_5 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='CIP_ND_5') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) CIP_ND_5 on x.ward=CIP_ND_5.ward_CIP_ND_5 and x.group_org=CIP_ND_5.group_org_CIP_ND_5 
 LEFT JOIN (SELECT ward ward_CLI_ND15, group_org group_org_CLI_ND15 , CASEWHEN(all_CLI_ND15>0, CEIL(ok_CLI_ND15*1000/all_CLI_ND15)/10,0) okproc_CLI_ND15, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_CLI_ND15) ok_CLI_ND15, SUM(a_CLI_ND15) all_CLI_ND15 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(CLI_ND15>s,1,0) s_CLI_ND15, CASEWHEN(s is null,0,1) a_CLI_ND15, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE CLI_ND15 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='CLI_ND15') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) CLI_ND15 on x.ward=CLI_ND15.ward_CLI_ND15 and x.group_org=CLI_ND15.group_org_CLI_ND15 
 LEFT JOIN (SELECT ward ward_CRO_ND30, group_org group_org_CRO_ND30 , CASEWHEN(all_CRO_ND30>0, CEIL(ok_CRO_ND30*1000/all_CRO_ND30)/10,0) okproc_CRO_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_CRO_ND30) ok_CRO_ND30, SUM(a_CRO_ND30) all_CRO_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(CRO_ND30>s,1,0) s_CRO_ND30, CASEWHEN(s is null,0,1) a_CRO_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE CRO_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='CRO_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) CRO_ND30 on x.ward=CRO_ND30.ward_CRO_ND30 and x.group_org=CRO_ND30.group_org_CRO_ND30 
 LEFT JOIN (SELECT ward ward_CSL_ND30, group_org group_org_CSL_ND30 , CASEWHEN(all_CSL_ND30>0, CEIL(ok_CSL_ND30*1000/all_CSL_ND30)/10,0) okproc_CSL_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_CSL_ND30) ok_CSL_ND30, SUM(a_CSL_ND30) all_CSL_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(CSL_ND30>s,1,0) s_CSL_ND30, CASEWHEN(s is null,0,1) a_CSL_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE CSL_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='CSL_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) CSL_ND30 on x.ward=CSL_ND30.ward_CSL_ND30 and x.group_org=CSL_ND30.group_org_CSL_ND30 
 LEFT JOIN (SELECT ward ward_CTR_ND10, group_org group_org_CTR_ND10 , CASEWHEN(all_CTR_ND10>0, CEIL(ok_CTR_ND10*1000/all_CTR_ND10)/10,0) okproc_CTR_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_CTR_ND10) ok_CTR_ND10, SUM(a_CTR_ND10) all_CTR_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(CTR_ND10>s,1,0) s_CTR_ND10, CASEWHEN(s is null,0,1) a_CTR_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE CTR_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='CTR_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) CTR_ND10 on x.ward=CTR_ND10.ward_CTR_ND10 and x.group_org=CTR_ND10.group_org_CTR_ND10 
 LEFT JOIN (SELECT ward ward_DOR_ND10, group_org group_org_DOR_ND10 , CASEWHEN(all_DOR_ND10>0, CEIL(ok_DOR_ND10*1000/all_DOR_ND10)/10,0) okproc_DOR_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_DOR_ND10) ok_DOR_ND10, SUM(a_DOR_ND10) all_DOR_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(DOR_ND10>s,1,0) s_DOR_ND10, CASEWHEN(s is null,0,1) a_DOR_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE DOR_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='DOR_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) DOR_ND10 on x.ward=DOR_ND10.ward_DOR_ND10 and x.group_org=DOR_ND10.group_org_DOR_ND10 
 LEFT JOIN (SELECT ward ward_ERY_ND15, group_org group_org_ERY_ND15 , CASEWHEN(all_ERY_ND15>0, CEIL(ok_ERY_ND15*1000/all_ERY_ND15)/10,0) okproc_ERY_ND15, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_ERY_ND15) ok_ERY_ND15, SUM(a_ERY_ND15) all_ERY_ND15 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(ERY_ND15>s,1,0) s_ERY_ND15, CASEWHEN(s is null,0,1) a_ERY_ND15, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE ERY_ND15 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='ERY_ND15') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) ERY_ND15 on x.ward=ERY_ND15.ward_ERY_ND15 and x.group_org=ERY_ND15.group_org_ERY_ND15 
 LEFT JOIN (SELECT ward ward_FEP_ND30, group_org group_org_FEP_ND30 , CASEWHEN(all_FEP_ND30>0, CEIL(ok_FEP_ND30*1000/all_FEP_ND30)/10,0) okproc_FEP_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_FEP_ND30) ok_FEP_ND30, SUM(a_FEP_ND30) all_FEP_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(FEP_ND30>s,1,0) s_FEP_ND30, CASEWHEN(s is null,0,1) a_FEP_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE FEP_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='FEP_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) FEP_ND30 on x.ward=FEP_ND30.ward_FEP_ND30 and x.group_org=FEP_ND30.group_org_FEP_ND30 
 LEFT JOIN (SELECT ward ward_FLU_ND25, group_org group_org_FLU_ND25 , CASEWHEN(all_FLU_ND25>0, CEIL(ok_FLU_ND25*1000/all_FLU_ND25)/10,0) okproc_FLU_ND25, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_FLU_ND25) ok_FLU_ND25, SUM(a_FLU_ND25) all_FLU_ND25 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(FLU_ND25>s,1,0) s_FLU_ND25, CASEWHEN(s is null,0,1) a_FLU_ND25, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE FLU_ND25 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='FLU_ND25') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) FLU_ND25 on x.ward=FLU_ND25.ward_FLU_ND25 and x.group_org=FLU_ND25.group_org_FLU_ND25 
 LEFT JOIN (SELECT ward ward_FOS_ND200, group_org group_org_FOS_ND200 , CASEWHEN(all_FOS_ND200>0, CEIL(ok_FOS_ND200*1000/all_FOS_ND200)/10,0) okproc_FOS_ND200, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_FOS_ND200) ok_FOS_ND200, SUM(a_FOS_ND200) all_FOS_ND200 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(FOS_ND200>s,1,0) s_FOS_ND200, CASEWHEN(s is null,0,1) a_FOS_ND200, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE FOS_ND200 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='FOS_ND200') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) FOS_ND200 on x.ward=FOS_ND200.ward_FOS_ND200 and x.group_org=FOS_ND200.group_org_FOS_ND200 
 LEFT JOIN (SELECT ward ward_GEN_ND10, group_org group_org_GEN_ND10 , CASEWHEN(all_GEN_ND10>0, CEIL(ok_GEN_ND10*1000/all_GEN_ND10)/10,0) okproc_GEN_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_GEN_ND10) ok_GEN_ND10, SUM(a_GEN_ND10) all_GEN_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(GEN_ND10>s,1,0) s_GEN_ND10, CASEWHEN(s is null,0,1) a_GEN_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE GEN_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='GEN_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) GEN_ND10 on x.ward=GEN_ND10.ward_GEN_ND10 and x.group_org=GEN_ND10.group_org_GEN_ND10 
 LEFT JOIN (SELECT ward ward_IPM_ND10, group_org group_org_IPM_ND10 , CASEWHEN(all_IPM_ND10>0, CEIL(ok_IPM_ND10*1000/all_IPM_ND10)/10,0) okproc_IPM_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_IPM_ND10) ok_IPM_ND10, SUM(a_IPM_ND10) all_IPM_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(IPM_ND10>s,1,0) s_IPM_ND10, CASEWHEN(s is null,0,1) a_IPM_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE IPM_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='IPM_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) IPM_ND10 on x.ward=IPM_ND10.ward_IPM_ND10 and x.group_org=IPM_ND10.group_org_IPM_ND10 
 LEFT JOIN (SELECT ward ward_ITR_ND8, group_org group_org_ITR_ND8 , CASEWHEN(all_ITR_ND8>0, CEIL(ok_ITR_ND8*1000/all_ITR_ND8)/10,0) okproc_ITR_ND8, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_ITR_ND8) ok_ITR_ND8, SUM(a_ITR_ND8) all_ITR_ND8 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(ITR_ND8>s,1,0) s_ITR_ND8, CASEWHEN(s is null,0,1) a_ITR_ND8, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE ITR_ND8 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='ITR_ND8') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) ITR_ND8 on x.ward=ITR_ND8.ward_ITR_ND8 and x.group_org=ITR_ND8.group_org_ITR_ND8 
 LEFT JOIN (SELECT ward ward_KET_ND15, group_org group_org_KET_ND15 , CASEWHEN(all_KET_ND15>0, CEIL(ok_KET_ND15*1000/all_KET_ND15)/10,0) okproc_KET_ND15, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_KET_ND15) ok_KET_ND15, SUM(a_KET_ND15) all_KET_ND15 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(KET_ND15>s,1,0) s_KET_ND15, CASEWHEN(s is null,0,1) a_KET_ND15, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE KET_ND15 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='KET_ND15') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) KET_ND15 on x.ward=KET_ND15.ward_KET_ND15 and x.group_org=KET_ND15.group_org_KET_ND15 
 LEFT JOIN (SELECT ward ward_LNZ_ND30, group_org group_org_LNZ_ND30 , CASEWHEN(all_LNZ_ND30>0, CEIL(ok_LNZ_ND30*1000/all_LNZ_ND30)/10,0) okproc_LNZ_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_LNZ_ND30) ok_LNZ_ND30, SUM(a_LNZ_ND30) all_LNZ_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(LNZ_ND30>s,1,0) s_LNZ_ND30, CASEWHEN(s is null,0,1) a_LNZ_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE LNZ_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='LNZ_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) LNZ_ND30 on x.ward=LNZ_ND30.ward_LNZ_ND30 and x.group_org=LNZ_ND30.group_org_LNZ_ND30 
 LEFT JOIN (SELECT ward ward_LVX_ND5, group_org group_org_LVX_ND5 , CASEWHEN(all_LVX_ND5>0, CEIL(ok_LVX_ND5*1000/all_LVX_ND5)/10,0) okproc_LVX_ND5, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_LVX_ND5) ok_LVX_ND5, SUM(a_LVX_ND5) all_LVX_ND5 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(LVX_ND5>s,1,0) s_LVX_ND5, CASEWHEN(s is null,0,1) a_LVX_ND5, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE LVX_ND5 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='LVX_ND5') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) LVX_ND5 on x.ward=LVX_ND5.ward_LVX_ND5 and x.group_org=LVX_ND5.group_org_LVX_ND5 
 LEFT JOIN (SELECT ward ward_MEM_ND10, group_org group_org_MEM_ND10 , CASEWHEN(all_MEM_ND10>0, CEIL(ok_MEM_ND10*1000/all_MEM_ND10)/10,0) okproc_MEM_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_MEM_ND10) ok_MEM_ND10, SUM(a_MEM_ND10) all_MEM_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(MEM_ND10>s,1,0) s_MEM_ND10, CASEWHEN(s is null,0,1) a_MEM_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE MEM_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='MEM_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) MEM_ND10 on x.ward=MEM_ND10.ward_MEM_ND10 and x.group_org=MEM_ND10.group_org_MEM_ND10 
 LEFT JOIN (SELECT ward ward_NIT_ND300, group_org group_org_NIT_ND300 , CASEWHEN(all_NIT_ND300>0, CEIL(ok_NIT_ND300*1000/all_NIT_ND300)/10,0) okproc_NIT_ND300, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_NIT_ND300) ok_NIT_ND300, SUM(a_NIT_ND300) all_NIT_ND300 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(NIT_ND300>s,1,0) s_NIT_ND300, CASEWHEN(s is null,0,1) a_NIT_ND300, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE NIT_ND300 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='NIT_ND300') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) NIT_ND300 on x.ward=NIT_ND300.ward_NIT_ND300 and x.group_org=NIT_ND300.group_org_NIT_ND300 
 LEFT JOIN (SELECT ward ward_NOR_ND10, group_org group_org_NOR_ND10 , CASEWHEN(all_NOR_ND10>0, CEIL(ok_NOR_ND10*1000/all_NOR_ND10)/10,0) okproc_NOR_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_NOR_ND10) ok_NOR_ND10, SUM(a_NOR_ND10) all_NOR_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(NOR_ND10>s,1,0) s_NOR_ND10, CASEWHEN(s is null,0,1) a_NOR_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE NOR_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='NOR_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) NOR_ND10 on x.ward=NOR_ND10.ward_NOR_ND10 and x.group_org=NOR_ND10.group_org_NOR_ND10 
 LEFT JOIN (SELECT ward ward_NYS_ND50, group_org group_org_NYS_ND50 , CASEWHEN(all_NYS_ND50>0, CEIL(ok_NYS_ND50*1000/all_NYS_ND50)/10,0) okproc_NYS_ND50, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_NYS_ND50) ok_NYS_ND50, SUM(a_NYS_ND50) all_NYS_ND50 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(NYS_ND50>s,1,0) s_NYS_ND50, CASEWHEN(s is null,0,1) a_NYS_ND50, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE NYS_ND50 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='NYS_ND50') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) NYS_ND50 on x.ward=NYS_ND50.ward_NYS_ND50 and x.group_org=NYS_ND50.group_org_NYS_ND50 
 LEFT JOIN (SELECT ward ward_OXA_ND1, group_org group_org_OXA_ND1 , CASEWHEN(all_OXA_ND1>0, CEIL(ok_OXA_ND1*1000/all_OXA_ND1)/10,0) okproc_OXA_ND1, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_OXA_ND1) ok_OXA_ND1, SUM(a_OXA_ND1) all_OXA_ND1 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(OXA_ND1>s,1,0) s_OXA_ND1, CASEWHEN(s is null,0,1) a_OXA_ND1, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE OXA_ND1 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='OXA_ND1') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) OXA_ND1 on x.ward=OXA_ND1.ward_OXA_ND1 and x.group_org=OXA_ND1.group_org_OXA_ND1 
 LEFT JOIN (SELECT ward ward_PIP_ND100, group_org group_org_PIP_ND100 , CASEWHEN(all_PIP_ND100>0, CEIL(ok_PIP_ND100*1000/all_PIP_ND100)/10,0) okproc_PIP_ND100, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_PIP_ND100) ok_PIP_ND100, SUM(a_PIP_ND100) all_PIP_ND100 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(PIP_ND100>s,1,0) s_PIP_ND100, CASEWHEN(s is null,0,1) a_PIP_ND100, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE PIP_ND100 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='PIP_ND100') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) PIP_ND100 on x.ward=PIP_ND100.ward_PIP_ND100 and x.group_org=PIP_ND100.group_org_PIP_ND100 
 LEFT JOIN (SELECT ward ward_PNV_ND10, group_org group_org_PNV_ND10 , CASEWHEN(all_PNV_ND10>0, CEIL(ok_PNV_ND10*1000/all_PNV_ND10)/10,0) okproc_PNV_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_PNV_ND10) ok_PNV_ND10, SUM(a_PNV_ND10) all_PNV_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(PNV_ND10>s,1,0) s_PNV_ND10, CASEWHEN(s is null,0,1) a_PNV_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE PNV_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='PNV_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) PNV_ND10 on x.ward=PNV_ND10.ward_PNV_ND10 and x.group_org=PNV_ND10.group_org_PNV_ND10 
 LEFT JOIN (SELECT ward ward_RIF_ND5, group_org group_org_RIF_ND5 , CASEWHEN(all_RIF_ND5>0, CEIL(ok_RIF_ND5*1000/all_RIF_ND5)/10,0) okproc_RIF_ND5, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_RIF_ND5) ok_RIF_ND5, SUM(a_RIF_ND5) all_RIF_ND5 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(RIF_ND5>s,1,0) s_RIF_ND5, CASEWHEN(s is null,0,1) a_RIF_ND5, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE RIF_ND5 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='RIF_ND5') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) RIF_ND5 on x.ward=RIF_ND5.ward_RIF_ND5 and x.group_org=RIF_ND5.group_org_RIF_ND5 
 LEFT JOIN (SELECT ward ward_SAM_ND10, group_org group_org_SAM_ND10 , CASEWHEN(all_SAM_ND10>0, CEIL(ok_SAM_ND10*1000/all_SAM_ND10)/10,0) okproc_SAM_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_SAM_ND10) ok_SAM_ND10, SUM(a_SAM_ND10) all_SAM_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(SAM_ND10>s,1,0) s_SAM_ND10, CASEWHEN(s is null,0,1) a_SAM_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE SAM_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='SAM_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) SAM_ND10 on x.ward=SAM_ND10.ward_SAM_ND10 and x.group_org=SAM_ND10.group_org_SAM_ND10 
 LEFT JOIN (SELECT ward ward_STR_ND10, group_org group_org_STR_ND10 , CASEWHEN(all_STR_ND10>0, CEIL(ok_STR_ND10*1000/all_STR_ND10)/10,0) okproc_STR_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_STR_ND10) ok_STR_ND10, SUM(a_STR_ND10) all_STR_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(STR_ND10>s,1,0) s_STR_ND10, CASEWHEN(s is null,0,1) a_STR_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE STR_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='STR_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) STR_ND10 on x.ward=STR_ND10.ward_STR_ND10 and x.group_org=STR_ND10.group_org_STR_ND10 
 LEFT JOIN (SELECT ward ward_TCY_ND30, group_org group_org_TCY_ND30 , CASEWHEN(all_TCY_ND30>0, CEIL(ok_TCY_ND30*1000/all_TCY_ND30)/10,0) okproc_TCY_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_TCY_ND30) ok_TCY_ND30, SUM(a_TCY_ND30) all_TCY_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(TCY_ND30>s,1,0) s_TCY_ND30, CASEWHEN(s is null,0,1) a_TCY_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE TCY_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='TCY_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) TCY_ND30 on x.ward=TCY_ND30.ward_TCY_ND30 and x.group_org=TCY_ND30.group_org_TCY_ND30 
 LEFT JOIN (SELECT ward ward_TOB_ND10, group_org group_org_TOB_ND10 , CASEWHEN(all_TOB_ND10>0, CEIL(ok_TOB_ND10*1000/all_TOB_ND10)/10,0) okproc_TOB_ND10, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_TOB_ND10) ok_TOB_ND10, SUM(a_TOB_ND10) all_TOB_ND10 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(TOB_ND10>s,1,0) s_TOB_ND10, CASEWHEN(s is null,0,1) a_TOB_ND10, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE TOB_ND10 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='TOB_ND10') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) TOB_ND10 on x.ward=TOB_ND10.ward_TOB_ND10 and x.group_org=TOB_ND10.group_org_TOB_ND10 
 LEFT JOIN (SELECT ward ward_VAN_ND30, group_org group_org_VAN_ND30 , CASEWHEN(all_VAN_ND30>0, CEIL(ok_VAN_ND30*1000/all_VAN_ND30)/10,0) okproc_VAN_ND30, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_VAN_ND30) ok_VAN_ND30, SUM(a_VAN_ND30) all_VAN_ND30 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(VAN_ND30>s,1,0) s_VAN_ND30, CASEWHEN(s is null,0,1) a_VAN_ND30, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE VAN_ND30 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='VAN_ND30') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) VAN_ND30 on x.ward=VAN_ND30.ward_VAN_ND30 and x.group_org=VAN_ND30.group_org_VAN_ND30 
 LEFT JOIN (SELECT ward ward_VOR_ND1, group_org group_org_VOR_ND1 , CASEWHEN(all_VOR_ND1>0, CEIL(ok_VOR_ND1*1000/all_VOR_ND1)/10,0) okproc_VOR_ND1, petri /*, x.* */ FROM (SELECT ward, group_org , COUNT(group_org) petri , SUM(s_VOR_ND1) ok_VOR_ND1, SUM(a_VOR_ND1) all_VOR_ND1 /*, x.* */ FROM ( SELECT ward, CASEWHEN(x.org is null, 'ani',x.org) group_org, amc_nd20, CASEWHEN(VOR_ND1>s,1,0) s_VOR_ND1, CASEWHEN(s is null,0,1) a_VOR_ND1, organism , x.* FROM (SELECT * FROM surgery17_3 WHERE VOR_ND1 IS NOT NULL) s LEFT JOIN  (SELECT roo.org org_in_rs, r.* FROM rs r, rs_org_org roo WHERE roo.rs_org=r.org AND code='VOR_ND1') x ON organism=org_in_rs) x GROUP BY ward, group_org) x ORDER BY ward, petri DESC ) VOR_ND1 on x.ward=VOR_ND1.ward_VOR_ND1 and x.group_org=VOR_ND1.group_org_VOR_ND1 
ORDER BY cnt_ward DESC, cnt_group_org DESC

